// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPbSMnzzj9TqMqkLp0Yjd-GwXCtHhL59Y',
    appId: '1:215783076176:android:2bdfe78b96a01d56fe7c55',
    messagingSenderId: '215783076176',
    projectId: 'bookhive-470d8',
    storageBucket: 'bookhive-470d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_SkjUqk9DEkmAKSS6JKhR1MGPFezoz6w',
    appId: '1:215783076176:ios:419d3264fd525416fe7c55',
    messagingSenderId: '215783076176',
    projectId: 'bookhive-470d8',
    storageBucket: 'bookhive-470d8.appspot.com',
    iosBundleId: 'com.example.bookHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMfbcs5P-Az0uN4iBwWR9pySOdeHL7EIs',
    appId: '1:215783076176:web:6af346b16289717dfe7c55',
    messagingSenderId: '215783076176',
    projectId: 'bookhive-470d8',
    authDomain: 'bookhive-470d8.firebaseapp.com',
    storageBucket: 'bookhive-470d8.appspot.com',
  );
}
